// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQqKWPVwdIMamchg3P1g2vGJdjZozexNI',
    appId: '1:359142820263:web:e5e6184885dcd6ec9dce82',
    messagingSenderId: '359142820263',
    projectId: 'cemungut-app',
    authDomain: 'cemungut-app.firebaseapp.com',
    storageBucket: 'cemungut-app.firebasestorage.app',
    measurementId: 'G-3RPKD7QQ8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7dzE0B44Qnf2QerQP3x38curZdaVCW-g',
    appId: '1:359142820263:android:041a281d1dac40129dce82',
    messagingSenderId: '359142820263',
    projectId: 'cemungut-app',
    storageBucket: 'cemungut-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-SXp4bzuI8SpT0WyoEg57ToWFki-NyAA',
    appId: '1:359142820263:ios:d0ddc2a9b22b6f8f9dce82',
    messagingSenderId: '359142820263',
    projectId: 'cemungut-app',
    storageBucket: 'cemungut-app.firebasestorage.app',
    iosBundleId: 'com.cemungut.cemungutApp',
  );

}